spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: false

